name: pipeline de integração contínua

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    steps:
    - name: Copia do repositório
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v5.3.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Execução dos testes
      run: mvn test

    - name: Criação do pacote
      run: mvn clean package -DskipTests
